server:
  port: ":8080"

chroma:
  address: "http://localhost:8000"

database:
  host: "localhost"
  port: 5433
  user: "user"
  password: "password"
  dbname: "news_subscriber"
  sslmode: "disable"

google:
  client_id: "730064113886-a2k35bb9t7ctplnhn9m2e98r2ljij3sr.apps.googleusercontent.com"

rabbitmq:
  url: "amqp://guest:guest@localhost:5672/"
