// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: auth.proto

package news_subscriber_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginStatus int32

const (
	LoginStatus_UNKNOWN      LoginStatus = 0
	LoginStatus_LOGGED_IN    LoginStatus = 1
	LoginStatus_NEEDS_INVITE LoginStatus = 2
)

// Enum value maps for LoginStatus.
var (
	LoginStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "LOGGED_IN",
		2: "NEEDS_INVITE",
	}
	LoginStatus_value = map[string]int32{
		"UNKNOWN":      0,
		"LOGGED_IN":    1,
		"NEEDS_INVITE": 2,
	}
)

func (x LoginStatus) Enum() *LoginStatus {
	p := new(LoginStatus)
	*p = x
	return p
}

func (x LoginStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LoginStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_auth_proto_enumTypes[0].Descriptor()
}

func (LoginStatus) Type() protoreflect.EnumType {
	return &file_auth_proto_enumTypes[0]
}

func (x LoginStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LoginStatus.Descriptor instead.
func (LoginStatus) EnumDescriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{0}
}

type GoogleLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdToken       string                 `protobuf:"bytes,1,opt,name=id_token,json=idToken,proto3" json:"id_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoogleLoginRequest) Reset() {
	*x = GoogleLoginRequest{}
	mi := &file_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoogleLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoogleLoginRequest) ProtoMessage() {}

func (x *GoogleLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoogleLoginRequest.ProtoReflect.Descriptor instead.
func (*GoogleLoginRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{0}
}

func (x *GoogleLoginRequest) GetIdToken() string {
	if x != nil {
		return x.IdToken
	}
	return ""
}

type GoogleLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        LoginStatus            `protobuf:"varint,1,opt,name=status,proto3,enum=news_subscriber.v1.LoginStatus" json:"status,omitempty"`
	SessionToken  string                 `protobuf:"bytes,2,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"` // Return email so frontend can show it
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoogleLoginResponse) Reset() {
	*x = GoogleLoginResponse{}
	mi := &file_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoogleLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoogleLoginResponse) ProtoMessage() {}

func (x *GoogleLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoogleLoginResponse.ProtoReflect.Descriptor instead.
func (*GoogleLoginResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{1}
}

func (x *GoogleLoginResponse) GetStatus() LoginStatus {
	if x != nil {
		return x.Status
	}
	return LoginStatus_UNKNOWN
}

func (x *GoogleLoginResponse) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *GoogleLoginResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GoogleLoginResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GoogleLoginResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CompleteSignupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdToken       string                 `protobuf:"bytes,1,opt,name=id_token,json=idToken,proto3" json:"id_token,omitempty"`
	InviteCode    string                 `protobuf:"bytes,2,opt,name=invite_code,json=inviteCode,proto3" json:"invite_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteSignupRequest) Reset() {
	*x = CompleteSignupRequest{}
	mi := &file_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteSignupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteSignupRequest) ProtoMessage() {}

func (x *CompleteSignupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteSignupRequest.ProtoReflect.Descriptor instead.
func (*CompleteSignupRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{2}
}

func (x *CompleteSignupRequest) GetIdToken() string {
	if x != nil {
		return x.IdToken
	}
	return ""
}

func (x *CompleteSignupRequest) GetInviteCode() string {
	if x != nil {
		return x.InviteCode
	}
	return ""
}

type CompleteSignupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionToken  string                 `protobuf:"bytes,1,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteSignupResponse) Reset() {
	*x = CompleteSignupResponse{}
	mi := &file_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteSignupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteSignupResponse) ProtoMessage() {}

func (x *CompleteSignupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteSignupResponse.ProtoReflect.Descriptor instead.
func (*CompleteSignupResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{3}
}

func (x *CompleteSignupResponse) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *CompleteSignupResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CompleteSignupResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_auth_proto protoreflect.FileDescriptor

const file_auth_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"auth.proto\x12\x12news_subscriber.v1\"/\n" +
	"\x12GoogleLoginRequest\x12\x19\n" +
	"\bid_token\x18\x01 \x01(\tR\aidToken\"\xb6\x01\n" +
	"\x13GoogleLoginResponse\x127\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1f.news_subscriber.v1.LoginStatusR\x06status\x12#\n" +
	"\rsession_token\x18\x02 \x01(\tR\fsessionToken\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\"S\n" +
	"\x15CompleteSignupRequest\x12\x19\n" +
	"\bid_token\x18\x01 \x01(\tR\aidToken\x12\x1f\n" +
	"\vinvite_code\x18\x02 \x01(\tR\n" +
	"inviteCode\"j\n" +
	"\x16CompleteSignupResponse\x12#\n" +
	"\rsession_token\x18\x01 \x01(\tR\fsessionToken\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name*;\n" +
	"\vLoginStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\r\n" +
	"\tLOGGED_IN\x10\x01\x12\x10\n" +
	"\fNEEDS_INVITE\x10\x022\xd6\x01\n" +
	"\vAuthService\x12^\n" +
	"\vGoogleLogin\x12&.news_subscriber.v1.GoogleLoginRequest\x1a'.news_subscriber.v1.GoogleLoginResponse\x12g\n" +
	"\x0eCompleteSignup\x12).news_subscriber.v1.CompleteSignupRequest\x1a*.news_subscriber.v1.CompleteSignupResponseB6Z4news-subscriber-core/api/proto/v1;news_subscriber_v1b\x06proto3"

var (
	file_auth_proto_rawDescOnce sync.Once
	file_auth_proto_rawDescData []byte
)

func file_auth_proto_rawDescGZIP() []byte {
	file_auth_proto_rawDescOnce.Do(func() {
		file_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_proto_rawDesc), len(file_auth_proto_rawDesc)))
	})
	return file_auth_proto_rawDescData
}

var file_auth_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_auth_proto_goTypes = []any{
	(LoginStatus)(0),               // 0: news_subscriber.v1.LoginStatus
	(*GoogleLoginRequest)(nil),     // 1: news_subscriber.v1.GoogleLoginRequest
	(*GoogleLoginResponse)(nil),    // 2: news_subscriber.v1.GoogleLoginResponse
	(*CompleteSignupRequest)(nil),  // 3: news_subscriber.v1.CompleteSignupRequest
	(*CompleteSignupResponse)(nil), // 4: news_subscriber.v1.CompleteSignupResponse
}
var file_auth_proto_depIdxs = []int32{
	0, // 0: news_subscriber.v1.GoogleLoginResponse.status:type_name -> news_subscriber.v1.LoginStatus
	1, // 1: news_subscriber.v1.AuthService.GoogleLogin:input_type -> news_subscriber.v1.GoogleLoginRequest
	3, // 2: news_subscriber.v1.AuthService.CompleteSignup:input_type -> news_subscriber.v1.CompleteSignupRequest
	2, // 3: news_subscriber.v1.AuthService.GoogleLogin:output_type -> news_subscriber.v1.GoogleLoginResponse
	4, // 4: news_subscriber.v1.AuthService.CompleteSignup:output_type -> news_subscriber.v1.CompleteSignupResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_auth_proto_init() }
func file_auth_proto_init() {
	if File_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_proto_rawDesc), len(file_auth_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_proto_goTypes,
		DependencyIndexes: file_auth_proto_depIdxs,
		EnumInfos:         file_auth_proto_enumTypes,
		MessageInfos:      file_auth_proto_msgTypes,
	}.Build()
	File_auth_proto = out.File
	file_auth_proto_goTypes = nil
	file_auth_proto_depIdxs = nil
}
