// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: report.proto

package news_subscriber_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Report struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"` // Markdown content
	CreatedAt     string                 `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Report) Reset() {
	*x = Report{}
	mi := &file_report_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Report) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Report) ProtoMessage() {}

func (x *Report) ProtoReflect() protoreflect.Message {
	mi := &file_report_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Report.ProtoReflect.Descriptor instead.
func (*Report) Descriptor() ([]byte, []int) {
	return file_report_proto_rawDescGZIP(), []int{0}
}

func (x *Report) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Report) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Report) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetLatestReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestReportRequest) Reset() {
	*x = GetLatestReportRequest{}
	mi := &file_report_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestReportRequest) ProtoMessage() {}

func (x *GetLatestReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_report_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestReportRequest.ProtoReflect.Descriptor instead.
func (*GetLatestReportRequest) Descriptor() ([]byte, []int) {
	return file_report_proto_rawDescGZIP(), []int{1}
}

func (x *GetLatestReportRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetLatestReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Report        *Report                `protobuf:"bytes,1,opt,name=report,proto3" json:"report,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestReportResponse) Reset() {
	*x = GetLatestReportResponse{}
	mi := &file_report_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestReportResponse) ProtoMessage() {}

func (x *GetLatestReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_report_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestReportResponse.ProtoReflect.Descriptor instead.
func (*GetLatestReportResponse) Descriptor() ([]byte, []int) {
	return file_report_proto_rawDescGZIP(), []int{2}
}

func (x *GetLatestReportResponse) GetReport() *Report {
	if x != nil {
		return x.Report
	}
	return nil
}

type GenerateReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateReportRequest) Reset() {
	*x = GenerateReportRequest{}
	mi := &file_report_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateReportRequest) ProtoMessage() {}

func (x *GenerateReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_report_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateReportRequest.ProtoReflect.Descriptor instead.
func (*GenerateReportRequest) Descriptor() ([]byte, []int) {
	return file_report_proto_rawDescGZIP(), []int{3}
}

func (x *GenerateReportRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GenerateReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Report        *Report                `protobuf:"bytes,1,opt,name=report,proto3" json:"report,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateReportResponse) Reset() {
	*x = GenerateReportResponse{}
	mi := &file_report_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateReportResponse) ProtoMessage() {}

func (x *GenerateReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_report_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateReportResponse.ProtoReflect.Descriptor instead.
func (*GenerateReportResponse) Descriptor() ([]byte, []int) {
	return file_report_proto_rawDescGZIP(), []int{4}
}

func (x *GenerateReportResponse) GetReport() *Report {
	if x != nil {
		return x.Report
	}
	return nil
}

var File_report_proto protoreflect.FileDescriptor

const file_report_proto_rawDesc = "" +
	"\n" +
	"\freport.proto\x12\x12news_subscriber.v1\"Q\n" +
	"\x06Report\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\tR\tcreatedAt\"1\n" +
	"\x16GetLatestReportRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"M\n" +
	"\x17GetLatestReportResponse\x122\n" +
	"\x06report\x18\x01 \x01(\v2\x1a.news_subscriber.v1.ReportR\x06report\"0\n" +
	"\x15GenerateReportRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"L\n" +
	"\x16GenerateReportResponse\x122\n" +
	"\x06report\x18\x01 \x01(\v2\x1a.news_subscriber.v1.ReportR\x06report2\xe4\x01\n" +
	"\rReportService\x12j\n" +
	"\x0fGetLatestReport\x12*.news_subscriber.v1.GetLatestReportRequest\x1a+.news_subscriber.v1.GetLatestReportResponse\x12g\n" +
	"\x0eGenerateReport\x12).news_subscriber.v1.GenerateReportRequest\x1a*.news_subscriber.v1.GenerateReportResponseB6Z4news-subscriber-core/api/proto/v1;news_subscriber_v1b\x06proto3"

var (
	file_report_proto_rawDescOnce sync.Once
	file_report_proto_rawDescData []byte
)

func file_report_proto_rawDescGZIP() []byte {
	file_report_proto_rawDescOnce.Do(func() {
		file_report_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_report_proto_rawDesc), len(file_report_proto_rawDesc)))
	})
	return file_report_proto_rawDescData
}

var file_report_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_report_proto_goTypes = []any{
	(*Report)(nil),                  // 0: news_subscriber.v1.Report
	(*GetLatestReportRequest)(nil),  // 1: news_subscriber.v1.GetLatestReportRequest
	(*GetLatestReportResponse)(nil), // 2: news_subscriber.v1.GetLatestReportResponse
	(*GenerateReportRequest)(nil),   // 3: news_subscriber.v1.GenerateReportRequest
	(*GenerateReportResponse)(nil),  // 4: news_subscriber.v1.GenerateReportResponse
}
var file_report_proto_depIdxs = []int32{
	0, // 0: news_subscriber.v1.GetLatestReportResponse.report:type_name -> news_subscriber.v1.Report
	0, // 1: news_subscriber.v1.GenerateReportResponse.report:type_name -> news_subscriber.v1.Report
	1, // 2: news_subscriber.v1.ReportService.GetLatestReport:input_type -> news_subscriber.v1.GetLatestReportRequest
	3, // 3: news_subscriber.v1.ReportService.GenerateReport:input_type -> news_subscriber.v1.GenerateReportRequest
	2, // 4: news_subscriber.v1.ReportService.GetLatestReport:output_type -> news_subscriber.v1.GetLatestReportResponse
	4, // 5: news_subscriber.v1.ReportService.GenerateReport:output_type -> news_subscriber.v1.GenerateReportResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_report_proto_init() }
func file_report_proto_init() {
	if File_report_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_report_proto_rawDesc), len(file_report_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_report_proto_goTypes,
		DependencyIndexes: file_report_proto_depIdxs,
		MessageInfos:      file_report_proto_msgTypes,
	}.Build()
	File_report_proto = out.File
	file_report_proto_goTypes = nil
	file_report_proto_depIdxs = nil
}
