// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: user.proto

package news_subscriber_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Preference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Preference) Reset() {
	*x = Preference{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Preference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Preference) ProtoMessage() {}

func (x *Preference) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Preference.ProtoReflect.Descriptor instead.
func (*Preference) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *Preference) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Preference) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type GetPreferencesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPreferencesRequest) Reset() {
	*x = GetPreferencesRequest{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPreferencesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPreferencesRequest) ProtoMessage() {}

func (x *GetPreferencesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPreferencesRequest.ProtoReflect.Descriptor instead.
func (*GetPreferencesRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *GetPreferencesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetPreferencesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Preferences   []*Preference          `protobuf:"bytes,1,rep,name=preferences,proto3" json:"preferences,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPreferencesResponse) Reset() {
	*x = GetPreferencesResponse{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPreferencesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPreferencesResponse) ProtoMessage() {}

func (x *GetPreferencesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPreferencesResponse.ProtoReflect.Descriptor instead.
func (*GetPreferencesResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *GetPreferencesResponse) GetPreferences() []*Preference {
	if x != nil {
		return x.Preferences
	}
	return nil
}

type AddPreferenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPreferenceRequest) Reset() {
	*x = AddPreferenceRequest{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPreferenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPreferenceRequest) ProtoMessage() {}

func (x *AddPreferenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPreferenceRequest.ProtoReflect.Descriptor instead.
func (*AddPreferenceRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

func (x *AddPreferenceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddPreferenceRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type AddPreferenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Preference    *Preference            `protobuf:"bytes,1,opt,name=preference,proto3" json:"preference,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPreferenceResponse) Reset() {
	*x = AddPreferenceResponse{}
	mi := &file_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPreferenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPreferenceResponse) ProtoMessage() {}

func (x *AddPreferenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPreferenceResponse.ProtoReflect.Descriptor instead.
func (*AddPreferenceResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{4}
}

func (x *AddPreferenceResponse) GetPreference() *Preference {
	if x != nil {
		return x.Preference
	}
	return nil
}

type UpdatePreferenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PreferenceId  string                 `protobuf:"bytes,2,opt,name=preference_id,json=preferenceId,proto3" json:"preference_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePreferenceRequest) Reset() {
	*x = UpdatePreferenceRequest{}
	mi := &file_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePreferenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePreferenceRequest) ProtoMessage() {}

func (x *UpdatePreferenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePreferenceRequest.ProtoReflect.Descriptor instead.
func (*UpdatePreferenceRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{5}
}

func (x *UpdatePreferenceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdatePreferenceRequest) GetPreferenceId() string {
	if x != nil {
		return x.PreferenceId
	}
	return ""
}

func (x *UpdatePreferenceRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type UpdatePreferenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Preference    *Preference            `protobuf:"bytes,1,opt,name=preference,proto3" json:"preference,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePreferenceResponse) Reset() {
	*x = UpdatePreferenceResponse{}
	mi := &file_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePreferenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePreferenceResponse) ProtoMessage() {}

func (x *UpdatePreferenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePreferenceResponse.ProtoReflect.Descriptor instead.
func (*UpdatePreferenceResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{6}
}

func (x *UpdatePreferenceResponse) GetPreference() *Preference {
	if x != nil {
		return x.Preference
	}
	return nil
}

type DeletePreferenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PreferenceId  string                 `protobuf:"bytes,2,opt,name=preference_id,json=preferenceId,proto3" json:"preference_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePreferenceRequest) Reset() {
	*x = DeletePreferenceRequest{}
	mi := &file_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePreferenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePreferenceRequest) ProtoMessage() {}

func (x *DeletePreferenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePreferenceRequest.ProtoReflect.Descriptor instead.
func (*DeletePreferenceRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{7}
}

func (x *DeletePreferenceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeletePreferenceRequest) GetPreferenceId() string {
	if x != nil {
		return x.PreferenceId
	}
	return ""
}

type DeletePreferenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePreferenceResponse) Reset() {
	*x = DeletePreferenceResponse{}
	mi := &file_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePreferenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePreferenceResponse) ProtoMessage() {}

func (x *DeletePreferenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePreferenceResponse.ProtoReflect.Descriptor instead.
func (*DeletePreferenceResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{8}
}

func (x *DeletePreferenceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\x12news_subscriber.v1\"6\n" +
	"\n" +
	"Preference\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"0\n" +
	"\x15GetPreferencesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"Z\n" +
	"\x16GetPreferencesResponse\x12@\n" +
	"\vpreferences\x18\x01 \x03(\v2\x1e.news_subscriber.v1.PreferenceR\vpreferences\"I\n" +
	"\x14AddPreferenceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"W\n" +
	"\x15AddPreferenceResponse\x12>\n" +
	"\n" +
	"preference\x18\x01 \x01(\v2\x1e.news_subscriber.v1.PreferenceR\n" +
	"preference\"q\n" +
	"\x17UpdatePreferenceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12#\n" +
	"\rpreference_id\x18\x02 \x01(\tR\fpreferenceId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\"Z\n" +
	"\x18UpdatePreferenceResponse\x12>\n" +
	"\n" +
	"preference\x18\x01 \x01(\v2\x1e.news_subscriber.v1.PreferenceR\n" +
	"preference\"W\n" +
	"\x17DeletePreferenceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12#\n" +
	"\rpreference_id\x18\x02 \x01(\tR\fpreferenceId\"4\n" +
	"\x18DeletePreferenceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xba\x03\n" +
	"\vUserService\x12g\n" +
	"\x0eGetPreferences\x12).news_subscriber.v1.GetPreferencesRequest\x1a*.news_subscriber.v1.GetPreferencesResponse\x12d\n" +
	"\rAddPreference\x12(.news_subscriber.v1.AddPreferenceRequest\x1a).news_subscriber.v1.AddPreferenceResponse\x12m\n" +
	"\x10UpdatePreference\x12+.news_subscriber.v1.UpdatePreferenceRequest\x1a,.news_subscriber.v1.UpdatePreferenceResponse\x12m\n" +
	"\x10DeletePreference\x12+.news_subscriber.v1.DeletePreferenceRequest\x1a,.news_subscriber.v1.DeletePreferenceResponseB6Z4news-subscriber-core/api/proto/v1;news_subscriber_v1b\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_user_proto_goTypes = []any{
	(*Preference)(nil),               // 0: news_subscriber.v1.Preference
	(*GetPreferencesRequest)(nil),    // 1: news_subscriber.v1.GetPreferencesRequest
	(*GetPreferencesResponse)(nil),   // 2: news_subscriber.v1.GetPreferencesResponse
	(*AddPreferenceRequest)(nil),     // 3: news_subscriber.v1.AddPreferenceRequest
	(*AddPreferenceResponse)(nil),    // 4: news_subscriber.v1.AddPreferenceResponse
	(*UpdatePreferenceRequest)(nil),  // 5: news_subscriber.v1.UpdatePreferenceRequest
	(*UpdatePreferenceResponse)(nil), // 6: news_subscriber.v1.UpdatePreferenceResponse
	(*DeletePreferenceRequest)(nil),  // 7: news_subscriber.v1.DeletePreferenceRequest
	(*DeletePreferenceResponse)(nil), // 8: news_subscriber.v1.DeletePreferenceResponse
}
var file_user_proto_depIdxs = []int32{
	0, // 0: news_subscriber.v1.GetPreferencesResponse.preferences:type_name -> news_subscriber.v1.Preference
	0, // 1: news_subscriber.v1.AddPreferenceResponse.preference:type_name -> news_subscriber.v1.Preference
	0, // 2: news_subscriber.v1.UpdatePreferenceResponse.preference:type_name -> news_subscriber.v1.Preference
	1, // 3: news_subscriber.v1.UserService.GetPreferences:input_type -> news_subscriber.v1.GetPreferencesRequest
	3, // 4: news_subscriber.v1.UserService.AddPreference:input_type -> news_subscriber.v1.AddPreferenceRequest
	5, // 5: news_subscriber.v1.UserService.UpdatePreference:input_type -> news_subscriber.v1.UpdatePreferenceRequest
	7, // 6: news_subscriber.v1.UserService.DeletePreference:input_type -> news_subscriber.v1.DeletePreferenceRequest
	2, // 7: news_subscriber.v1.UserService.GetPreferences:output_type -> news_subscriber.v1.GetPreferencesResponse
	4, // 8: news_subscriber.v1.UserService.AddPreference:output_type -> news_subscriber.v1.AddPreferenceResponse
	6, // 9: news_subscriber.v1.UserService.UpdatePreference:output_type -> news_subscriber.v1.UpdatePreferenceResponse
	8, // 10: news_subscriber.v1.UserService.DeletePreference:output_type -> news_subscriber.v1.DeletePreferenceResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
