// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.1
//   protoc               v6.33.1
// source: auth.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";

export const protobufPackage = "news_subscriber.v1";

export enum LoginStatus {
  UNKNOWN = 0,
  LOGGED_IN = 1,
  NEEDS_INVITE = 2,
  UNRECOGNIZED = -1,
}

export function loginStatusFromJSON(object: any): LoginStatus {
  switch (object) {
    case 0:
    case "UNKNOWN":
      return LoginStatus.UNKNOWN;
    case 1:
    case "LOGGED_IN":
      return LoginStatus.LOGGED_IN;
    case 2:
    case "NEEDS_INVITE":
      return LoginStatus.NEEDS_INVITE;
    case -1:
    case "UNRECOGNIZED":
    default:
      return LoginStatus.UNRECOGNIZED;
  }
}

export function loginStatusToJSON(object: LoginStatus): string {
  switch (object) {
    case LoginStatus.UNKNOWN:
      return "UNKNOWN";
    case LoginStatus.LOGGED_IN:
      return "LOGGED_IN";
    case LoginStatus.NEEDS_INVITE:
      return "NEEDS_INVITE";
    case LoginStatus.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface GoogleLoginRequest {
  idToken: string;
}

export interface GoogleLoginResponse {
  status: LoginStatus;
  sessionToken: string;
  userId: string;
  /** Return email so frontend can show it */
  email: string;
}

export interface CompleteSignupRequest {
  idToken: string;
  inviteCode: string;
}

export interface CompleteSignupResponse {
  sessionToken: string;
  userId: string;
}

function createBaseGoogleLoginRequest(): GoogleLoginRequest {
  return { idToken: "" };
}

export const GoogleLoginRequest: MessageFns<GoogleLoginRequest> = {
  encode(message: GoogleLoginRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.idToken !== "") {
      writer.uint32(10).string(message.idToken);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GoogleLoginRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGoogleLoginRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.idToken = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GoogleLoginRequest {
    return { idToken: isSet(object.idToken) ? globalThis.String(object.idToken) : "" };
  },

  toJSON(message: GoogleLoginRequest): unknown {
    const obj: any = {};
    if (message.idToken !== "") {
      obj.idToken = message.idToken;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GoogleLoginRequest>, I>>(base?: I): GoogleLoginRequest {
    return GoogleLoginRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GoogleLoginRequest>, I>>(object: I): GoogleLoginRequest {
    const message = createBaseGoogleLoginRequest();
    message.idToken = object.idToken ?? "";
    return message;
  },
};

function createBaseGoogleLoginResponse(): GoogleLoginResponse {
  return { status: 0, sessionToken: "", userId: "", email: "" };
}

export const GoogleLoginResponse: MessageFns<GoogleLoginResponse> = {
  encode(message: GoogleLoginResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.status !== 0) {
      writer.uint32(8).int32(message.status);
    }
    if (message.sessionToken !== "") {
      writer.uint32(18).string(message.sessionToken);
    }
    if (message.userId !== "") {
      writer.uint32(26).string(message.userId);
    }
    if (message.email !== "") {
      writer.uint32(34).string(message.email);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GoogleLoginResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGoogleLoginResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.sessionToken = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.email = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GoogleLoginResponse {
    return {
      status: isSet(object.status) ? loginStatusFromJSON(object.status) : 0,
      sessionToken: isSet(object.sessionToken) ? globalThis.String(object.sessionToken) : "",
      userId: isSet(object.userId) ? globalThis.String(object.userId) : "",
      email: isSet(object.email) ? globalThis.String(object.email) : "",
    };
  },

  toJSON(message: GoogleLoginResponse): unknown {
    const obj: any = {};
    if (message.status !== 0) {
      obj.status = loginStatusToJSON(message.status);
    }
    if (message.sessionToken !== "") {
      obj.sessionToken = message.sessionToken;
    }
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.email !== "") {
      obj.email = message.email;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GoogleLoginResponse>, I>>(base?: I): GoogleLoginResponse {
    return GoogleLoginResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GoogleLoginResponse>, I>>(object: I): GoogleLoginResponse {
    const message = createBaseGoogleLoginResponse();
    message.status = object.status ?? 0;
    message.sessionToken = object.sessionToken ?? "";
    message.userId = object.userId ?? "";
    message.email = object.email ?? "";
    return message;
  },
};

function createBaseCompleteSignupRequest(): CompleteSignupRequest {
  return { idToken: "", inviteCode: "" };
}

export const CompleteSignupRequest: MessageFns<CompleteSignupRequest> = {
  encode(message: CompleteSignupRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.idToken !== "") {
      writer.uint32(10).string(message.idToken);
    }
    if (message.inviteCode !== "") {
      writer.uint32(18).string(message.inviteCode);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CompleteSignupRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCompleteSignupRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.idToken = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.inviteCode = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CompleteSignupRequest {
    return {
      idToken: isSet(object.idToken) ? globalThis.String(object.idToken) : "",
      inviteCode: isSet(object.inviteCode) ? globalThis.String(object.inviteCode) : "",
    };
  },

  toJSON(message: CompleteSignupRequest): unknown {
    const obj: any = {};
    if (message.idToken !== "") {
      obj.idToken = message.idToken;
    }
    if (message.inviteCode !== "") {
      obj.inviteCode = message.inviteCode;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CompleteSignupRequest>, I>>(base?: I): CompleteSignupRequest {
    return CompleteSignupRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CompleteSignupRequest>, I>>(object: I): CompleteSignupRequest {
    const message = createBaseCompleteSignupRequest();
    message.idToken = object.idToken ?? "";
    message.inviteCode = object.inviteCode ?? "";
    return message;
  },
};

function createBaseCompleteSignupResponse(): CompleteSignupResponse {
  return { sessionToken: "", userId: "" };
}

export const CompleteSignupResponse: MessageFns<CompleteSignupResponse> = {
  encode(message: CompleteSignupResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.sessionToken !== "") {
      writer.uint32(10).string(message.sessionToken);
    }
    if (message.userId !== "") {
      writer.uint32(18).string(message.userId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CompleteSignupResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCompleteSignupResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.sessionToken = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CompleteSignupResponse {
    return {
      sessionToken: isSet(object.sessionToken) ? globalThis.String(object.sessionToken) : "",
      userId: isSet(object.userId) ? globalThis.String(object.userId) : "",
    };
  },

  toJSON(message: CompleteSignupResponse): unknown {
    const obj: any = {};
    if (message.sessionToken !== "") {
      obj.sessionToken = message.sessionToken;
    }
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CompleteSignupResponse>, I>>(base?: I): CompleteSignupResponse {
    return CompleteSignupResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CompleteSignupResponse>, I>>(object: I): CompleteSignupResponse {
    const message = createBaseCompleteSignupResponse();
    message.sessionToken = object.sessionToken ?? "";
    message.userId = object.userId ?? "";
    return message;
  },
};

export type AuthServiceService = typeof AuthServiceService;
export const AuthServiceService = {
  googleLogin: {
    path: "/news_subscriber.v1.AuthService/GoogleLogin",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GoogleLoginRequest): Buffer => Buffer.from(GoogleLoginRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GoogleLoginRequest => GoogleLoginRequest.decode(value),
    responseSerialize: (value: GoogleLoginResponse): Buffer => Buffer.from(GoogleLoginResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GoogleLoginResponse => GoogleLoginResponse.decode(value),
  },
  completeSignup: {
    path: "/news_subscriber.v1.AuthService/CompleteSignup",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: CompleteSignupRequest): Buffer =>
      Buffer.from(CompleteSignupRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): CompleteSignupRequest => CompleteSignupRequest.decode(value),
    responseSerialize: (value: CompleteSignupResponse): Buffer =>
      Buffer.from(CompleteSignupResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): CompleteSignupResponse => CompleteSignupResponse.decode(value),
  },
} as const;

export interface AuthServiceServer extends UntypedServiceImplementation {
  googleLogin: handleUnaryCall<GoogleLoginRequest, GoogleLoginResponse>;
  completeSignup: handleUnaryCall<CompleteSignupRequest, CompleteSignupResponse>;
}

export interface AuthServiceClient extends Client {
  googleLogin(
    request: GoogleLoginRequest,
    callback: (error: ServiceError | null, response: GoogleLoginResponse) => void,
  ): ClientUnaryCall;
  googleLogin(
    request: GoogleLoginRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GoogleLoginResponse) => void,
  ): ClientUnaryCall;
  googleLogin(
    request: GoogleLoginRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GoogleLoginResponse) => void,
  ): ClientUnaryCall;
  completeSignup(
    request: CompleteSignupRequest,
    callback: (error: ServiceError | null, response: CompleteSignupResponse) => void,
  ): ClientUnaryCall;
  completeSignup(
    request: CompleteSignupRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: CompleteSignupResponse) => void,
  ): ClientUnaryCall;
  completeSignup(
    request: CompleteSignupRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: CompleteSignupResponse) => void,
  ): ClientUnaryCall;
}

export const AuthServiceClient = makeGenericClientConstructor(
  AuthServiceService,
  "news_subscriber.v1.AuthService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): AuthServiceClient;
  service: typeof AuthServiceService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
