// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.1
//   protoc               v6.33.1
// source: report.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";

export const protobufPackage = "news_subscriber.v1";

export interface Report {
  id: string;
  /** Markdown content */
  content: string;
  createdAt: string;
}

export interface GetLatestReportRequest {
  userId: string;
}

export interface GetLatestReportResponse {
  report: Report | undefined;
}

export interface GenerateReportRequest {
  userId: string;
}

export interface GenerateReportResponse {
  report: Report | undefined;
}

function createBaseReport(): Report {
  return { id: "", content: "", createdAt: "" };
}

export const Report: MessageFns<Report> = {
  encode(message: Report, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.content !== "") {
      writer.uint32(18).string(message.content);
    }
    if (message.createdAt !== "") {
      writer.uint32(26).string(message.createdAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Report {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseReport();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.content = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.createdAt = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Report {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      content: isSet(object.content) ? globalThis.String(object.content) : "",
      createdAt: isSet(object.createdAt) ? globalThis.String(object.createdAt) : "",
    };
  },

  toJSON(message: Report): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.content !== "") {
      obj.content = message.content;
    }
    if (message.createdAt !== "") {
      obj.createdAt = message.createdAt;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Report>, I>>(base?: I): Report {
    return Report.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Report>, I>>(object: I): Report {
    const message = createBaseReport();
    message.id = object.id ?? "";
    message.content = object.content ?? "";
    message.createdAt = object.createdAt ?? "";
    return message;
  },
};

function createBaseGetLatestReportRequest(): GetLatestReportRequest {
  return { userId: "" };
}

export const GetLatestReportRequest: MessageFns<GetLatestReportRequest> = {
  encode(message: GetLatestReportRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetLatestReportRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetLatestReportRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetLatestReportRequest {
    return { userId: isSet(object.userId) ? globalThis.String(object.userId) : "" };
  },

  toJSON(message: GetLatestReportRequest): unknown {
    const obj: any = {};
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetLatestReportRequest>, I>>(base?: I): GetLatestReportRequest {
    return GetLatestReportRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetLatestReportRequest>, I>>(object: I): GetLatestReportRequest {
    const message = createBaseGetLatestReportRequest();
    message.userId = object.userId ?? "";
    return message;
  },
};

function createBaseGetLatestReportResponse(): GetLatestReportResponse {
  return { report: undefined };
}

export const GetLatestReportResponse: MessageFns<GetLatestReportResponse> = {
  encode(message: GetLatestReportResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.report !== undefined) {
      Report.encode(message.report, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetLatestReportResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetLatestReportResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.report = Report.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetLatestReportResponse {
    return { report: isSet(object.report) ? Report.fromJSON(object.report) : undefined };
  },

  toJSON(message: GetLatestReportResponse): unknown {
    const obj: any = {};
    if (message.report !== undefined) {
      obj.report = Report.toJSON(message.report);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetLatestReportResponse>, I>>(base?: I): GetLatestReportResponse {
    return GetLatestReportResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetLatestReportResponse>, I>>(object: I): GetLatestReportResponse {
    const message = createBaseGetLatestReportResponse();
    message.report = (object.report !== undefined && object.report !== null)
      ? Report.fromPartial(object.report)
      : undefined;
    return message;
  },
};

function createBaseGenerateReportRequest(): GenerateReportRequest {
  return { userId: "" };
}

export const GenerateReportRequest: MessageFns<GenerateReportRequest> = {
  encode(message: GenerateReportRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GenerateReportRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGenerateReportRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GenerateReportRequest {
    return { userId: isSet(object.userId) ? globalThis.String(object.userId) : "" };
  },

  toJSON(message: GenerateReportRequest): unknown {
    const obj: any = {};
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GenerateReportRequest>, I>>(base?: I): GenerateReportRequest {
    return GenerateReportRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GenerateReportRequest>, I>>(object: I): GenerateReportRequest {
    const message = createBaseGenerateReportRequest();
    message.userId = object.userId ?? "";
    return message;
  },
};

function createBaseGenerateReportResponse(): GenerateReportResponse {
  return { report: undefined };
}

export const GenerateReportResponse: MessageFns<GenerateReportResponse> = {
  encode(message: GenerateReportResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.report !== undefined) {
      Report.encode(message.report, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GenerateReportResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGenerateReportResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.report = Report.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GenerateReportResponse {
    return { report: isSet(object.report) ? Report.fromJSON(object.report) : undefined };
  },

  toJSON(message: GenerateReportResponse): unknown {
    const obj: any = {};
    if (message.report !== undefined) {
      obj.report = Report.toJSON(message.report);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GenerateReportResponse>, I>>(base?: I): GenerateReportResponse {
    return GenerateReportResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GenerateReportResponse>, I>>(object: I): GenerateReportResponse {
    const message = createBaseGenerateReportResponse();
    message.report = (object.report !== undefined && object.report !== null)
      ? Report.fromPartial(object.report)
      : undefined;
    return message;
  },
};

export type ReportServiceService = typeof ReportServiceService;
export const ReportServiceService = {
  getLatestReport: {
    path: "/news_subscriber.v1.ReportService/GetLatestReport",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GetLatestReportRequest): Buffer =>
      Buffer.from(GetLatestReportRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetLatestReportRequest => GetLatestReportRequest.decode(value),
    responseSerialize: (value: GetLatestReportResponse): Buffer =>
      Buffer.from(GetLatestReportResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetLatestReportResponse => GetLatestReportResponse.decode(value),
  },
  generateReport: {
    path: "/news_subscriber.v1.ReportService/GenerateReport",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GenerateReportRequest): Buffer =>
      Buffer.from(GenerateReportRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GenerateReportRequest => GenerateReportRequest.decode(value),
    responseSerialize: (value: GenerateReportResponse): Buffer =>
      Buffer.from(GenerateReportResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GenerateReportResponse => GenerateReportResponse.decode(value),
  },
} as const;

export interface ReportServiceServer extends UntypedServiceImplementation {
  getLatestReport: handleUnaryCall<GetLatestReportRequest, GetLatestReportResponse>;
  generateReport: handleUnaryCall<GenerateReportRequest, GenerateReportResponse>;
}

export interface ReportServiceClient extends Client {
  getLatestReport(
    request: GetLatestReportRequest,
    callback: (error: ServiceError | null, response: GetLatestReportResponse) => void,
  ): ClientUnaryCall;
  getLatestReport(
    request: GetLatestReportRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GetLatestReportResponse) => void,
  ): ClientUnaryCall;
  getLatestReport(
    request: GetLatestReportRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GetLatestReportResponse) => void,
  ): ClientUnaryCall;
  generateReport(
    request: GenerateReportRequest,
    callback: (error: ServiceError | null, response: GenerateReportResponse) => void,
  ): ClientUnaryCall;
  generateReport(
    request: GenerateReportRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GenerateReportResponse) => void,
  ): ClientUnaryCall;
  generateReport(
    request: GenerateReportRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GenerateReportResponse) => void,
  ): ClientUnaryCall;
}

export const ReportServiceClient = makeGenericClientConstructor(
  ReportServiceService,
  "news_subscriber.v1.ReportService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): ReportServiceClient;
  service: typeof ReportServiceService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
