// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.1
//   protoc               v6.33.1
// source: user.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";

export const protobufPackage = "news_subscriber.v1";

export interface Preference {
  id: string;
  content: string;
}

export interface GetPreferencesRequest {
  userId: string;
}

export interface GetPreferencesResponse {
  preferences: Preference[];
}

export interface AddPreferenceRequest {
  userId: string;
  content: string;
}

export interface AddPreferenceResponse {
  preference: Preference | undefined;
}

export interface UpdatePreferenceRequest {
  userId: string;
  preferenceId: string;
  content: string;
}

export interface UpdatePreferenceResponse {
  preference: Preference | undefined;
}

export interface DeletePreferenceRequest {
  userId: string;
  preferenceId: string;
}

export interface DeletePreferenceResponse {
  success: boolean;
}

function createBasePreference(): Preference {
  return { id: "", content: "" };
}

export const Preference: MessageFns<Preference> = {
  encode(message: Preference, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.content !== "") {
      writer.uint32(18).string(message.content);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Preference {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePreference();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.content = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Preference {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      content: isSet(object.content) ? globalThis.String(object.content) : "",
    };
  },

  toJSON(message: Preference): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.content !== "") {
      obj.content = message.content;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Preference>, I>>(base?: I): Preference {
    return Preference.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Preference>, I>>(object: I): Preference {
    const message = createBasePreference();
    message.id = object.id ?? "";
    message.content = object.content ?? "";
    return message;
  },
};

function createBaseGetPreferencesRequest(): GetPreferencesRequest {
  return { userId: "" };
}

export const GetPreferencesRequest: MessageFns<GetPreferencesRequest> = {
  encode(message: GetPreferencesRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetPreferencesRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetPreferencesRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetPreferencesRequest {
    return { userId: isSet(object.userId) ? globalThis.String(object.userId) : "" };
  },

  toJSON(message: GetPreferencesRequest): unknown {
    const obj: any = {};
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetPreferencesRequest>, I>>(base?: I): GetPreferencesRequest {
    return GetPreferencesRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetPreferencesRequest>, I>>(object: I): GetPreferencesRequest {
    const message = createBaseGetPreferencesRequest();
    message.userId = object.userId ?? "";
    return message;
  },
};

function createBaseGetPreferencesResponse(): GetPreferencesResponse {
  return { preferences: [] };
}

export const GetPreferencesResponse: MessageFns<GetPreferencesResponse> = {
  encode(message: GetPreferencesResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.preferences) {
      Preference.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetPreferencesResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetPreferencesResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.preferences.push(Preference.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetPreferencesResponse {
    return {
      preferences: globalThis.Array.isArray(object?.preferences)
        ? object.preferences.map((e: any) => Preference.fromJSON(e))
        : [],
    };
  },

  toJSON(message: GetPreferencesResponse): unknown {
    const obj: any = {};
    if (message.preferences?.length) {
      obj.preferences = message.preferences.map((e) => Preference.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetPreferencesResponse>, I>>(base?: I): GetPreferencesResponse {
    return GetPreferencesResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetPreferencesResponse>, I>>(object: I): GetPreferencesResponse {
    const message = createBaseGetPreferencesResponse();
    message.preferences = object.preferences?.map((e) => Preference.fromPartial(e)) || [];
    return message;
  },
};

function createBaseAddPreferenceRequest(): AddPreferenceRequest {
  return { userId: "", content: "" };
}

export const AddPreferenceRequest: MessageFns<AddPreferenceRequest> = {
  encode(message: AddPreferenceRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    if (message.content !== "") {
      writer.uint32(18).string(message.content);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AddPreferenceRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAddPreferenceRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.content = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AddPreferenceRequest {
    return {
      userId: isSet(object.userId) ? globalThis.String(object.userId) : "",
      content: isSet(object.content) ? globalThis.String(object.content) : "",
    };
  },

  toJSON(message: AddPreferenceRequest): unknown {
    const obj: any = {};
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.content !== "") {
      obj.content = message.content;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AddPreferenceRequest>, I>>(base?: I): AddPreferenceRequest {
    return AddPreferenceRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AddPreferenceRequest>, I>>(object: I): AddPreferenceRequest {
    const message = createBaseAddPreferenceRequest();
    message.userId = object.userId ?? "";
    message.content = object.content ?? "";
    return message;
  },
};

function createBaseAddPreferenceResponse(): AddPreferenceResponse {
  return { preference: undefined };
}

export const AddPreferenceResponse: MessageFns<AddPreferenceResponse> = {
  encode(message: AddPreferenceResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.preference !== undefined) {
      Preference.encode(message.preference, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AddPreferenceResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAddPreferenceResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.preference = Preference.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AddPreferenceResponse {
    return { preference: isSet(object.preference) ? Preference.fromJSON(object.preference) : undefined };
  },

  toJSON(message: AddPreferenceResponse): unknown {
    const obj: any = {};
    if (message.preference !== undefined) {
      obj.preference = Preference.toJSON(message.preference);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AddPreferenceResponse>, I>>(base?: I): AddPreferenceResponse {
    return AddPreferenceResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AddPreferenceResponse>, I>>(object: I): AddPreferenceResponse {
    const message = createBaseAddPreferenceResponse();
    message.preference = (object.preference !== undefined && object.preference !== null)
      ? Preference.fromPartial(object.preference)
      : undefined;
    return message;
  },
};

function createBaseUpdatePreferenceRequest(): UpdatePreferenceRequest {
  return { userId: "", preferenceId: "", content: "" };
}

export const UpdatePreferenceRequest: MessageFns<UpdatePreferenceRequest> = {
  encode(message: UpdatePreferenceRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    if (message.preferenceId !== "") {
      writer.uint32(18).string(message.preferenceId);
    }
    if (message.content !== "") {
      writer.uint32(26).string(message.content);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdatePreferenceRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdatePreferenceRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.preferenceId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.content = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdatePreferenceRequest {
    return {
      userId: isSet(object.userId) ? globalThis.String(object.userId) : "",
      preferenceId: isSet(object.preferenceId) ? globalThis.String(object.preferenceId) : "",
      content: isSet(object.content) ? globalThis.String(object.content) : "",
    };
  },

  toJSON(message: UpdatePreferenceRequest): unknown {
    const obj: any = {};
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.preferenceId !== "") {
      obj.preferenceId = message.preferenceId;
    }
    if (message.content !== "") {
      obj.content = message.content;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdatePreferenceRequest>, I>>(base?: I): UpdatePreferenceRequest {
    return UpdatePreferenceRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdatePreferenceRequest>, I>>(object: I): UpdatePreferenceRequest {
    const message = createBaseUpdatePreferenceRequest();
    message.userId = object.userId ?? "";
    message.preferenceId = object.preferenceId ?? "";
    message.content = object.content ?? "";
    return message;
  },
};

function createBaseUpdatePreferenceResponse(): UpdatePreferenceResponse {
  return { preference: undefined };
}

export const UpdatePreferenceResponse: MessageFns<UpdatePreferenceResponse> = {
  encode(message: UpdatePreferenceResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.preference !== undefined) {
      Preference.encode(message.preference, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdatePreferenceResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdatePreferenceResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.preference = Preference.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdatePreferenceResponse {
    return { preference: isSet(object.preference) ? Preference.fromJSON(object.preference) : undefined };
  },

  toJSON(message: UpdatePreferenceResponse): unknown {
    const obj: any = {};
    if (message.preference !== undefined) {
      obj.preference = Preference.toJSON(message.preference);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdatePreferenceResponse>, I>>(base?: I): UpdatePreferenceResponse {
    return UpdatePreferenceResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdatePreferenceResponse>, I>>(object: I): UpdatePreferenceResponse {
    const message = createBaseUpdatePreferenceResponse();
    message.preference = (object.preference !== undefined && object.preference !== null)
      ? Preference.fromPartial(object.preference)
      : undefined;
    return message;
  },
};

function createBaseDeletePreferenceRequest(): DeletePreferenceRequest {
  return { userId: "", preferenceId: "" };
}

export const DeletePreferenceRequest: MessageFns<DeletePreferenceRequest> = {
  encode(message: DeletePreferenceRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    if (message.preferenceId !== "") {
      writer.uint32(18).string(message.preferenceId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeletePreferenceRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeletePreferenceRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.preferenceId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeletePreferenceRequest {
    return {
      userId: isSet(object.userId) ? globalThis.String(object.userId) : "",
      preferenceId: isSet(object.preferenceId) ? globalThis.String(object.preferenceId) : "",
    };
  },

  toJSON(message: DeletePreferenceRequest): unknown {
    const obj: any = {};
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.preferenceId !== "") {
      obj.preferenceId = message.preferenceId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DeletePreferenceRequest>, I>>(base?: I): DeletePreferenceRequest {
    return DeletePreferenceRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeletePreferenceRequest>, I>>(object: I): DeletePreferenceRequest {
    const message = createBaseDeletePreferenceRequest();
    message.userId = object.userId ?? "";
    message.preferenceId = object.preferenceId ?? "";
    return message;
  },
};

function createBaseDeletePreferenceResponse(): DeletePreferenceResponse {
  return { success: false };
}

export const DeletePreferenceResponse: MessageFns<DeletePreferenceResponse> = {
  encode(message: DeletePreferenceResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeletePreferenceResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeletePreferenceResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeletePreferenceResponse {
    return { success: isSet(object.success) ? globalThis.Boolean(object.success) : false };
  },

  toJSON(message: DeletePreferenceResponse): unknown {
    const obj: any = {};
    if (message.success !== false) {
      obj.success = message.success;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DeletePreferenceResponse>, I>>(base?: I): DeletePreferenceResponse {
    return DeletePreferenceResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeletePreferenceResponse>, I>>(object: I): DeletePreferenceResponse {
    const message = createBaseDeletePreferenceResponse();
    message.success = object.success ?? false;
    return message;
  },
};

export type UserServiceService = typeof UserServiceService;
export const UserServiceService = {
  getPreferences: {
    path: "/news_subscriber.v1.UserService/GetPreferences",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GetPreferencesRequest): Buffer =>
      Buffer.from(GetPreferencesRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetPreferencesRequest => GetPreferencesRequest.decode(value),
    responseSerialize: (value: GetPreferencesResponse): Buffer =>
      Buffer.from(GetPreferencesResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetPreferencesResponse => GetPreferencesResponse.decode(value),
  },
  addPreference: {
    path: "/news_subscriber.v1.UserService/AddPreference",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: AddPreferenceRequest): Buffer => Buffer.from(AddPreferenceRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): AddPreferenceRequest => AddPreferenceRequest.decode(value),
    responseSerialize: (value: AddPreferenceResponse): Buffer =>
      Buffer.from(AddPreferenceResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): AddPreferenceResponse => AddPreferenceResponse.decode(value),
  },
  updatePreference: {
    path: "/news_subscriber.v1.UserService/UpdatePreference",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: UpdatePreferenceRequest): Buffer =>
      Buffer.from(UpdatePreferenceRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): UpdatePreferenceRequest => UpdatePreferenceRequest.decode(value),
    responseSerialize: (value: UpdatePreferenceResponse): Buffer =>
      Buffer.from(UpdatePreferenceResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): UpdatePreferenceResponse => UpdatePreferenceResponse.decode(value),
  },
  deletePreference: {
    path: "/news_subscriber.v1.UserService/DeletePreference",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: DeletePreferenceRequest): Buffer =>
      Buffer.from(DeletePreferenceRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): DeletePreferenceRequest => DeletePreferenceRequest.decode(value),
    responseSerialize: (value: DeletePreferenceResponse): Buffer =>
      Buffer.from(DeletePreferenceResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): DeletePreferenceResponse => DeletePreferenceResponse.decode(value),
  },
} as const;

export interface UserServiceServer extends UntypedServiceImplementation {
  getPreferences: handleUnaryCall<GetPreferencesRequest, GetPreferencesResponse>;
  addPreference: handleUnaryCall<AddPreferenceRequest, AddPreferenceResponse>;
  updatePreference: handleUnaryCall<UpdatePreferenceRequest, UpdatePreferenceResponse>;
  deletePreference: handleUnaryCall<DeletePreferenceRequest, DeletePreferenceResponse>;
}

export interface UserServiceClient extends Client {
  getPreferences(
    request: GetPreferencesRequest,
    callback: (error: ServiceError | null, response: GetPreferencesResponse) => void,
  ): ClientUnaryCall;
  getPreferences(
    request: GetPreferencesRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GetPreferencesResponse) => void,
  ): ClientUnaryCall;
  getPreferences(
    request: GetPreferencesRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GetPreferencesResponse) => void,
  ): ClientUnaryCall;
  addPreference(
    request: AddPreferenceRequest,
    callback: (error: ServiceError | null, response: AddPreferenceResponse) => void,
  ): ClientUnaryCall;
  addPreference(
    request: AddPreferenceRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: AddPreferenceResponse) => void,
  ): ClientUnaryCall;
  addPreference(
    request: AddPreferenceRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: AddPreferenceResponse) => void,
  ): ClientUnaryCall;
  updatePreference(
    request: UpdatePreferenceRequest,
    callback: (error: ServiceError | null, response: UpdatePreferenceResponse) => void,
  ): ClientUnaryCall;
  updatePreference(
    request: UpdatePreferenceRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: UpdatePreferenceResponse) => void,
  ): ClientUnaryCall;
  updatePreference(
    request: UpdatePreferenceRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: UpdatePreferenceResponse) => void,
  ): ClientUnaryCall;
  deletePreference(
    request: DeletePreferenceRequest,
    callback: (error: ServiceError | null, response: DeletePreferenceResponse) => void,
  ): ClientUnaryCall;
  deletePreference(
    request: DeletePreferenceRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: DeletePreferenceResponse) => void,
  ): ClientUnaryCall;
  deletePreference(
    request: DeletePreferenceRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: DeletePreferenceResponse) => void,
  ): ClientUnaryCall;
}

export const UserServiceClient = makeGenericClientConstructor(
  UserServiceService,
  "news_subscriber.v1.UserService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): UserServiceClient;
  service: typeof UserServiceService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
